Repository Hyundai-Charowner/Sac-BE, pull requests merged in 2023-12, with the labels that each got.

#2 feat: 사용자가 Google로그인 후 token(spring make) 수령
  build.gradle
  src/main/java/site/sac/HomeController.java
  src/main/java/site/sac/controller/HomeController.java
  src/main/java/site/sac/controller/LogInController.java
  src/main/java/site/sac/dto/GoogleOAuthDTO.java
  src/main/java/site/sac/dto/JWTPayloadDTO.java
  src/main/java/site/sac/dto/TokenDTO.java
  src/main/java/site/sac/dto/UsersDTO.java
  src/main/java/site/sac/mapper/TokenMapper.java
  src/main/java/site/sac/mapper/UsersMapper.java
  src/main/java/site/sac/service/UsersService.java
  src/main/java/site/sac/service/UsersServiceImpl.java
  src/main/resources/site/sac/mapper/TokenMapper.xml
  src/main/resources/site/sac/mapper/UsersMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 🐯Feature

#8 7 feat 스프링 게시글 작성 및 조회 api 추가
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/controller/UserLikeBoardController.java
  src/main/java/site/sac/dto/BoardDTO.java
  src/main/java/site/sac/dto/PostDTO.java
  src/main/java/site/sac/dto/ReplyDTO.java
  src/main/java/site/sac/dto/UserLikeBoardDTO.java
  src/main/java/site/sac/dto/UserLikePostLikeDTO.java
  src/main/java/site/sac/dto/UsersDTO.java
  src/main/java/site/sac/mapper/BoardMapper.java
  src/main/java/site/sac/mapper/PostMapper.java
  src/main/java/site/sac/mapper/ReplyMapper.java
  src/main/java/site/sac/mapper/UserLikeBoardMapper.java
  src/main/java/site/sac/mapper/UserLikePostMapper.java
  src/main/java/site/sac/service/PostService.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/UserLikeBoardService.java
  src/main/java/site/sac/service/UserLikeBoardServiceImpl.java
  src/main/java/site/sac/service/UsersServiceImpl.java
  src/main/resources/site/sac/mapper/BoardMapper.xml
  src/main/resources/site/sac/mapper/PostMapper.xml
  src/main/resources/site/sac/mapper/ReplyMapper.xml
  src/main/resources/site/sac/mapper/UserLikeBoardMapper.xml
  src/main/resources/site/sac/mapper/UserLikePostMapper.xml
  src/main/resources/site/sac/mapper/UsersMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/test/java/site/sac/BoardMapperTest.java
  src/test/java/site/sac/PostMapperTest.java
  src/test/java/site/sac/ReplyMapperTest.java
  src/test/java/site/sac/UserLikeBoardMapperTest.java
  src/test/java/site/sac/UserLikePostMapperTest.java
  src/test/resources/root-context.xml
Labels: 🐯Feature

#10 [Fix] Request Mapping url 수정
  src/main/java/site/sac/controller/LogInController.java
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/controller/UserLikeBoardController.java
  src/main/java/site/sac/dto/BoardDTO.java
  src/main/java/site/sac/dto/PostDTO.java
  src/main/java/site/sac/dto/ReplyDTO.java
  src/main/java/site/sac/dto/UserLikeBoardDTO.java
  src/main/java/site/sac/dto/UserLikePostLikeDTO.java
  src/main/java/site/sac/dto/UsersDTO.java
  src/main/java/site/sac/mapper/BoardMapper.java
  src/main/java/site/sac/mapper/PostMapper.java
  src/main/java/site/sac/mapper/ReplyMapper.java
  src/main/java/site/sac/mapper/UserLikeBoardMapper.java
  src/main/java/site/sac/mapper/UserLikePostMapper.java
  src/main/java/site/sac/service/PostService.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/UserLikeBoardService.java
  src/main/java/site/sac/service/UserLikeBoardServiceImpl.java
  src/main/java/site/sac/service/UsersServiceImpl.java
  src/main/resources/site/sac/mapper/BoardMapper.xml
  src/main/resources/site/sac/mapper/PostMapper.xml
  src/main/resources/site/sac/mapper/ReplyMapper.xml
  src/main/resources/site/sac/mapper/UserLikeBoardMapper.xml
  src/main/resources/site/sac/mapper/UserLikePostMapper.xml
  src/main/resources/site/sac/mapper/UsersMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/test/java/site/sac/BoardMapperTest.java
  src/test/java/site/sac/PostMapperTest.java
  src/test/java/site/sac/ReplyMapperTest.java
  src/test/java/site/sac/UserLikeBoardMapperTest.java
  src/test/java/site/sac/UserLikePostMapperTest.java
  src/test/resources/root-context.xml
Labels: 🐞Bug/fix

#12 Feat basic mapper
  src/main/java/site/sac/controller/HomeController.java
  src/main/java/site/sac/controller/LogInController.java
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/controller/ReplyController.java
  src/main/java/site/sac/controller/UserLikeBoardController.java
  src/main/java/site/sac/controller/UserLikePostController.java
  src/main/java/site/sac/controller/UsersController.java
  src/main/java/site/sac/dto/JWTPayloadDTO.java
  src/main/java/site/sac/dto/UserLikePostDTO.java
  src/main/java/site/sac/dto/UsersDTO.java
  src/main/java/site/sac/mapper/ReplyMapper.java
  src/main/java/site/sac/mapper/UserLikePostMapper.java
  src/main/java/site/sac/service/PostService.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/ReplyService.java
  src/main/java/site/sac/service/ReplyServiceImpl.java
  src/main/java/site/sac/service/UserLikePostService.java
  src/main/java/site/sac/service/UserLikePostServiceImpl.java
  src/main/java/site/sac/service/UsersService.java
  src/main/java/site/sac/service/UsersServiceImpl.java
  src/main/resources/site/sac/mapper/PostMapper.xml
  src/main/resources/site/sac/mapper/ReplyMapper.xml
  src/main/resources/site/sac/mapper/TokenMapper.xml
  src/test/java/site/sac/UserLikePostMapperTest.java
Labels: 🐯Feature

#15 14 web cors 해결하기
  src/main/java/site/sac/configurer/WebMvcConfig.java
  src/main/java/site/sac/controller/LogInController.java
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/controller/ReplyController.java
  src/main/java/site/sac/controller/UserLikePostController.java
  src/main/java/site/sac/mapper/PostMapper.java
  src/main/java/site/sac/service/PostService.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/UserLikePostService.java
  src/main/resources/site/sac/mapper/PostMapper.xml
Labels: 🐯Feature

#19 fix: api url 변경
  src/main/java/site/sac/controller/PostController.java
  src/main/webapp/WEB-INF/web.xml
Labels: 🐞Bug/fix

#20 배포
  src/main/java/site/sac/controller/PostController.java
  src/main/webapp/WEB-INF/web.xml
Labels: 🎉Realease

#22 feat: interceptor 적용
  src/main/java/site/sac/interceptor/AuthInterceptor.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: 🐯Feature

#26 [Fix] exception 처리
  src/main/java/site/sac/controller/LogInController.java
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/controller/ReplyController.java
  src/main/java/site/sac/controller/UserLikeBoardController.java
  src/main/java/site/sac/controller/UserLikePostController.java
  src/main/java/site/sac/controller/UsersController.java
  src/main/java/site/sac/exception/GlobalExceptionHandler.java
  src/main/java/site/sac/interceptor/AuthInterceptor.java
  src/main/java/site/sac/service/PostService.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/ReplyService.java
  src/main/java/site/sac/service/ReplyServiceImpl.java
  src/main/java/site/sac/service/UserLikeBoardService.java
  src/main/java/site/sac/service/UserLikeBoardServiceImpl.java
  src/main/java/site/sac/service/UserLikePostService.java
  src/main/java/site/sac/service/UserLikePostServiceImpl.java
  src/main/java/site/sac/service/UsersService.java
  src/main/java/site/sac/service/UsersServiceImpl.java
Labels: 🐞Bug/fix

#28 hotfix: build error 수정
  src/main/java/site/sac/controller/PostController.java
Labels: 🐞Bug/fix

#29 hotfix
  src/main/java/site/sac/controller/PostController.java
Labels: 🐞Bug/fix

#31 [fix] 게시글에 필요한 내용 추가, 조회수, 종아요 수 증가
  src/main/java/site/sac/dto/PostResponseDTO.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/UserLikePostServiceImpl.java
  src/main/resources/site/sac/mapper/PostResponseMapper.xml
Labels: 🐞Bug/fix

#32 배포하기
  src/main/java/site/sac/dto/PostResponseDTO.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/UserLikePostServiceImpl.java
  src/main/resources/site/sac/mapper/PostResponseMapper.xml
Labels: 🎉Realease

#34 fix : 게시글 관련 api 주소 및 userId 추가
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/controller/UserLikePostController.java
  src/main/java/site/sac/dto/ReplyDTO.java
  src/main/java/site/sac/mapper/PostMapper.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/UserLikePostService.java
  src/main/java/site/sac/service/UserLikePostServiceImpl.java
  src/main/resources/site/sac/mapper/PostMapper.xml
Labels: 🐞Bug/fix

#36 fix : reply, userlike api
  src/main/java/site/sac/controller/ReplyController.java
  src/main/java/site/sac/controller/UserLikeBoardController.java
  src/main/java/site/sac/controller/UsersController.java
  src/main/java/site/sac/service/ReplyService.java
  src/main/java/site/sac/service/ReplyServiceImpl.java
  src/main/java/site/sac/service/UserLikeBoardService.java
  src/main/java/site/sac/service/UserLikeBoardServiceImpl.java
Labels: 🐞Bug/fix

#37 배포 연결
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/controller/ReplyController.java
  src/main/java/site/sac/controller/UserLikeBoardController.java
  src/main/java/site/sac/controller/UserLikePostController.java
  src/main/java/site/sac/controller/UsersController.java
  src/main/java/site/sac/dto/ReplyDTO.java
  src/main/java/site/sac/mapper/PostMapper.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/ReplyService.java
  src/main/java/site/sac/service/ReplyServiceImpl.java
  src/main/java/site/sac/service/UserLikeBoardService.java
  src/main/java/site/sac/service/UserLikeBoardServiceImpl.java
  src/main/java/site/sac/service/UserLikePostService.java
  src/main/java/site/sac/service/UserLikePostServiceImpl.java
  src/main/resources/site/sac/mapper/PostMapper.xml
Labels: 🎉Realease

#38 fix: cors 에러 수정
  src/main/java/site/sac/configuration/WebConfig.java
Labels: 🐞Bug/fix

#40 fix: cors 수정
  src/main/java/site/sac/configuration/WebConfig.java
  src/main/resources/site/sac/config/cors-config.xml
Labels: 🐞Bug/fix

#42 fix: cors 수정
  src/main/java/site/sac/configuration/WebConfig.java
Labels: 🐞Bug/fix

#43 [Fix] reply add
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/domain/Criteria.java
  src/main/java/site/sac/dto/ReplyResponseDTO.java
  src/main/java/site/sac/mapper/ReplyResponseMapper.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/ReplyServiceImpl.java
  src/main/resources/site/sac/mapper/PostResponseMapper.xml
  src/main/resources/site/sac/mapper/ReplyResponseMapper.xml
Labels: 🐞Bug/fix

#44 fix: cors
  .github/workflows/gradle.yml
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/domain/Criteria.java
  src/main/java/site/sac/dto/ReplyResponseDTO.java
  src/main/java/site/sac/mapper/ReplyResponseMapper.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/java/site/sac/service/ReplyServiceImpl.java
  src/main/resources/site/sac/mapper/PostResponseMapper.xml
  src/main/resources/site/sac/mapper/ReplyResponseMapper.xml
Labels: 🐞Bug/fix

#45 fix: cors 수정
  src/main/java/site/sac/configuration/WebConfig.java
Labels: 🐞Bug/fix

#47 [feature] api 추가
  src/main/java/site/sac/controller/RankingController.java
  src/main/java/site/sac/mapper/BoardMapper.java
  src/main/java/site/sac/mapper/RankingMapper.java
  src/main/java/site/sac/service/RankingService.java
  src/main/java/site/sac/service/RankingServiceImpl.java
  src/main/resources/site/sac/mapper/RankingMapper.xml
Labels: 🐯Feature

#48 배포환경
  src/main/java/site/sac/controller/RankingController.java
  src/main/java/site/sac/mapper/BoardMapper.java
  src/main/java/site/sac/mapper/RankingMapper.java
  src/main/java/site/sac/service/RankingService.java
  src/main/java/site/sac/service/RankingServiceImpl.java
  src/main/resources/site/sac/mapper/RankingMapper.xml
Labels: 🎉Realease

#50 fix: cors 수정
  src/main/java/site/sac/configuration/WebConfig.java
  src/main/resources/site/sac/config/cors-config.xml
Labels: 🐞Bug/fix

#52 fix: post date type 변경
  src/main/resources/site/sac/mapper/PostResponseMapper.xml
Labels: 🐞Bug/fix

#53 fix: post date type 변경
  src/main/java/site/sac/dto/PostResponseDTO.java
  src/main/resources/site/sac/mapper/PostResponseMapper.xml
Labels: 🐞Bug/fix

#54 Develop feat merge
  src/main/java/site/sac/controller/LogInController.java
  src/main/java/site/sac/controller/PostController.java
  src/main/java/site/sac/controller/UserLikeBoardController.java
  src/main/java/site/sac/mapper/PostResponseMapper.java
  src/main/java/site/sac/service/PostResponseService.java
  src/main/java/site/sac/service/PostResponseServiceImpl.java
  src/main/java/site/sac/service/PostService.java
  src/main/java/site/sac/service/PostServiceImpl.java
  src/main/resources/site/sac/mapper/PostResponseMapper.xml
Labels: 🐞Bug/fix
